name: macOS Runner Test

on:
  push:
    branches:
      - main

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
      - name: Show macOS version
        run: sw_vers

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Confirm runner working
        run: echo "✅ macOS runner is active and your workflow is running, Khuram bhai!"
