name: iOS Build (MyFirstiOSApp)

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: |
          xcodebuild -version
          xcode-select -p

      - name: Build iOS app
        run: |
          xcodebuild \
            -scheme MyFirstiOSApp \
            -sdk iphoneos \
            -configuration Release \
            clean build \
            CODE_SIGNING_ALLOWED=NO

      - name: Create IPA file
        run: |
          mkdir -p build
          xcodebuild \
            -scheme MyFirstiOSApp \
            -sdk iphoneos \
            -configuration Release \
            -archivePath build/MyFirstiOSApp.xcarchive \
            archive CODE_SIGNING_ALLOWED=NO

          xcodebuild -exportArchive \
            -archivePath build/
